# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: changshun
google_analytics: changshun

avatar: /img/touxiang.jpg

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Changshun's Blog

description: Stylish Jekyll Theme
author:
  name: chosen.shih
  email: chosen.shih@gmail.com
  github: changshun
  twitter: allenstoneshi
  bio: A Master in WISE, XMU
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
